import { SITE_URL } from "../../config/config";

const CJK_FONTS: Record<string, string> = {
  zh: "Microsoft YaHei",
  ja: "Yu Gothic",
  ko: "Malgun Gothic",
};

function baseCode(code: string): string {
  return (code || "").split("-")[0].toLowerCase();
}

export function isCjkFont(code: string): boolean {
  return baseCode(code) in CJK_FONTS;
}

export function defaultFontFor(langCode: string): string {
  return CJK_FONTS[baseCode(langCode)] || "Arial";
}

export function assStyleNameFor(langCode: string): string {
  return (langCode || "secondary").replace(/[^A-Za-z0-9-]/g, "");
}

export const DEFAULT_ASS_STYLE = "Default";

export function cueStyleName(cueSettings: string | undefined): string {
  return cueSettings?.split("|")[1] || DEFAULT_ASS_STYLE;
}

export function secondaryStyleName(baseStyle: string, langCode: string): string {
  return `${baseStyle}-${assStyleNameFor(langCode)}`;
}

export interface AssFontPlan {
  primaryFont: string;
  primarySize: number;
  secondaryFont: string;
  secondarySize: number;
}

export type AssFontPreset = "desktop" | "mobile" | "custom";

const MOBILE_SCALE = 1.35;

const SECONDARY_SIZE_RATIO = 0.8;

function secondarySizeFor(primarySize: number, equalSize: boolean, customSize?: number): number {
  if (equalSize) return primarySize;
  return customSize || Math.round(primarySize * SECONDARY_SIZE_RATIO);
}

export interface AssFontOverrides {
  preset?: AssFontPreset;
  customPrimarySize?: number;
  customSecondarySize?: number;
}

export function defaultAssFontPlan(primaryLang: string, secondaryLang: string, bilingual: boolean, equalSize: boolean, overrides?: AssFontOverrides): AssFontPlan {
  const primaryFont = defaultFontFor(primaryLang);
  const secondaryFont = defaultFontFor(secondaryLang);
  let primarySize = bilingual ? (isCjkFont(primaryLang) ? 70 : 48) : 20;
  if (overrides?.preset === "mobile") primarySize = Math.round(primarySize * MOBILE_SCALE);
  else if (overrides?.preset === "custom" && overrides.customPrimarySize) primarySize = overrides.customPrimarySize;
  const secondarySize = bilingual ? secondarySizeFor(primarySize, equalSize, overrides?.preset === "custom" ? overrides.customSecondarySize : undefined) : primarySize;
  return { primaryFont, primarySize, secondaryFont, secondarySize };
}

const STYLE_FORMAT_FIELDS = ["Name", "Fontname", "Fontsize", "PrimaryColour", "SecondaryColour", "OutlineColour", "BackColour", "Bold", "Italic", "Underline", "StrikeOut", "ScaleX", "ScaleY", "Spacing", "Angle", "BorderStyle", "Outline", "Shadow", "Alignment", "MarginL", "MarginR", "MarginV", "Encoding"];
const STYLE_ROW_PATTERN = /^(Format|Style):/i;

interface StyleColumns {
  name: number;
  font: number;
  size: number;
}

function styleColumns(formatLine: string | undefined): StyleColumns {
  const fields = formatLine ? splitStyleFields(formatLine).map((f) => f.toLowerCase()) : STYLE_FORMAT_FIELDS.map((f) => f.toLowerCase());
  const at = (field: string, fallback: number) => {
    const index = fields.indexOf(field);
    return index === -1 ? fallback : index;
  };
  return { name: at("name", 0), font: at("fontname", 1), size: at("fontsize", 2) };
}

function splitStyleFields(line: string): string[] {
  return line.slice(line.indexOf(":") + 1).split(",").map((field) => field.trim());
}

export interface AssMergeOptions {
  bilingual: boolean;
  usedStyles: string[];
  sourceLang: string;
  primaryLang: string;
  secondaryLang: string;
  equalSize: boolean;
  preset?: AssFontPreset;
  customPrimarySize?: number;
  customSecondarySize?: number;
}

function primarySizeFor(originalSize: number, preset: AssFontPreset | undefined, customSize?: number): number {
  if (preset === "mobile") return Math.round(originalSize * MOBILE_SCALE);
  if (preset === "custom" && customSize) return customSize;
  return originalSize;
}

export function mergeIntoOriginalAssHeader(originalHeader: string, options: AssMergeOptions): string {
  const { bilingual, usedStyles, sourceLang, primaryLang, secondaryLang, equalSize, preset, customPrimarySize, customSecondarySize } = options;
  const lines = originalHeader.split("\n");

  const scriptInfoIdx = lines.findIndex((l) => l.trim() === "[Script Info]");
  if (scriptInfoIdx !== -1) {
    let end = scriptInfoIdx + 1;
    while (end < lines.length && lines[end].trim().startsWith(";")) end++;
    lines.splice(scriptInfoIdx + 1, end - (scriptInfoIdx + 1), `; Translated and generated by Montage Subtitle Translator v${__APP_VERSION__} (${SITE_URL})`);
  }

  const stylesIdx = lines.findIndex((l) => l.trim() === "[V4+ Styles]");
  if (stylesIdx === -1) return lines.join("\n");
  let sectionEnd = stylesIdx + 1;
  while (sectionEnd < lines.length && !lines[sectionEnd].trim().startsWith("[")) sectionEnd++;

  const rows = lines.slice(stylesIdx + 1, sectionEnd).map((line) => line.trim());
  const columns = styleColumns(rows.find((row) => /^Format:/i.test(row)));
  const definedStyles = new Set(rows.filter((row) => /^Style:/i.test(row)).map((row) => splitStyleFields(row)[columns.name]));

  const fontFor = (lang: string, current: string) => (isCjkFont(lang) && !isCjkFont(sourceLang) ? defaultFontFor(lang) : current);
  const restyle = (fields: string[], name: string, lang: string, size: number) => {
    const next = [...fields];
    next[columns.name] = name;
    next[columns.font] = fontFor(lang, fields[columns.font]);
    next[columns.size] = String(size);
    return `Style: ${next.join(",")}`;
  };

  const secondaryLines: string[] = [];
  let insertAt = stylesIdx + 1;
  for (let i = stylesIdx + 1; i < sectionEnd; i++) {
    if (!STYLE_ROW_PATTERN.test(lines[i].trim())) continue;
    insertAt = i + 1;
    if (!/^Style:/i.test(lines[i].trim())) continue;
    const fields = splitStyleFields(lines[i]);
    const name = fields[columns.name];
    if (!usedStyles.includes(name)) continue;
    const primarySize = primarySizeFor(Number(fields[columns.size]) || 0, preset, customPrimarySize);
    const secondaryName = secondaryStyleName(name, secondaryLang);
    if (bilingual && !definedStyles.has(secondaryName)) {
      const secondarySize = secondarySizeFor(primarySize, equalSize, preset === "custom" ? customSecondarySize : undefined);
      secondaryLines.push(restyle(fields, secondaryName, secondaryLang, secondarySize));
    }
    lines[i] = restyle(fields, name, primaryLang, primarySize);
  }
  lines.splice(insertAt, 0, ...secondaryLines);

  return lines.join("\n");
}

export interface AssHeaderOptions {
  bilingual: boolean;
  fonts: AssFontPlan;
  secondaryLang: string;
}

export function buildAssHeader(options: AssHeaderOptions): string {
  const { bilingual, fonts, secondaryLang } = options;
  const lines = [
    "[Script Info]",
    `; Translated and generated by Montage Subtitle Translator v${__APP_VERSION__} (${SITE_URL})`,
    "Title: ",
    "ScriptType: v4.00+",
    "PlayDepth: 0",
    "ScaledBorderAndShadow: Yes",
    "",
    "[V4+ Styles]",
    `Format: ${STYLE_FORMAT_FIELDS.join(", ")}`,
  ];
  if (bilingual) {
    lines.push(`Style: ${DEFAULT_ASS_STYLE},${fonts.primaryFont},${fonts.primarySize},&H00F5F5F5,&HF0000000,&H00000000,&H32000000,0,0,0,0,100,100,0,0,1,1.5,1,2,5,5,15,1`);
    lines.push(`Style: ${secondaryStyleName(DEFAULT_ASS_STYLE, secondaryLang)},${fonts.secondaryFont},${fonts.secondarySize},&H00F5F5F5,&HF0000000,&H00000000,&H32000000,0,0,0,0,100,100,0,0,1,1.5,1,2,5,5,15,1`);
  } else {
    lines.push(`Style: ${DEFAULT_ASS_STYLE},${fonts.primaryFont},${fonts.primarySize},&H00FFFFFF,&H0000FFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,2,10,10,10,1`);
  }
  lines.push("", "[Events]", "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text");
  return lines.join("\n");
}
