export { docPages, docCategories, staticPages } from "virtual:docs-content";
export type { DocPage, StaticPage } from "../../vite-plugins/docsContent";
export { PAGE_IDS } from "../router.pages";
export type { PageId } from "../router.pages";
export { LOCALES, DEFAULT_LOCALE } from "../i18n/locales.config";
export type { LocaleCode } from "../i18n/locales.config";
export { translate } from "../i18n/dictionaries";
export { TITLE_KEYS, DESCRIPTION_KEYS } from "./metaKeys";
export { renderDocument } from "./documentShell";
export type { ShellContext } from "./shellMarkup";
export { renderDocsListBody, renderDocsDetailBody, sortPages } from "./docsMarkup";
export { renderStaticPageBody } from "./staticPageMarkup";
export { renderJsRequiredBody } from "./jsRequiredMarkup";
