ALTER TABLE ip_shield ADD COLUMN malformed_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ip_shield ADD COLUMN handshake_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ip_shield ADD COLUMN completed_count INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS global_budget (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  day_bucket INTEGER NOT NULL DEFAULT 0,
  used INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO global_budget (id, day_bucket, used) VALUES (1, 0, 0);
